<?php


class TweetTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var \TwitterApp\Model\Tweet
     */
    private $tweet;

    public function setUp()
    {
        $tweet = new \TwitterApp\Model\Tweet('esto es un tweet');
        $this->tweet = $tweet;

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function tweet_without_inreply()
    {
        $date = new DateTime('2018-06-25 16:03:38');
        $this->tweet->setCreatedAt($date);

        $this->assertArraySubset([
            'created_at' => $date->format('D M d H:i:s O Y'),
            'text' => 'esto es un tweet'
        ], $this->tweet->toArray());
    }

    /**
     * @test
     */
    public function tweet_with_inreply()
    {
        $this->tweet->setCreatedAt(new DateTime('2018-06-25 16:03:38'));
        $this->tweet->setInReply(true);

        $this->assertArrayHasKey('in_reply', $this->tweet->toArray());
        $this->assertArraySubset([
            'in_reply' => [
                'id' => null,
                'name' => null,
            ]
        ], $this->tweet->toArray());
        //$this->assertEquals($tweetArrayExpected, $this->tweet->toArray());
    }

    /**
     * @test
     */
    public function set_in_reply_is_valid()
    {
        $this->tweet->setInReply(true);

        $this->assertTrue($this->tweet->isInReply());
    }

    /**
     * @test
     */
    public function set_in_reply_invalid_throw_exception()
    {
        $this->expectExceptionMessage('in_reply most be of type boolean');

        $this->tweet->setInReply('hola');
    }

    /**
     * @test
     */
    public function toArray_most_return_an_array_tweet()
    {

        $this->tweet->setCreatedAt(new DateTime('2018-06-25 16:03:38'));
        $tweetArrayExpected = [
            'created_at' => 'Mon Jun 25 16:03:38 +0000 2018',
            'text' => 'esto es un tweet'
        ];

        $this->assertEquals($tweetArrayExpected, $this->tweet->toArray());

    }

    /**
     * @test
     */
    public function set_created_at_return_valid_datetime()
    {
        $date = new DateTime('2018-06-25 16:03:38');

        $tweet = new \TwitterApp\Model\Tweet('esto es un tweet');
        $tweet->setCreatedAt($date);

        $dateExpected = 'Mon Jun 25 16:03:38 +0000 2018';

        $this->assertEquals($dateExpected, $tweet->getCreatedAt());

    }

}